channels:
  - conda-forge
dependencies:
  - python>=3.10.6
  - matplotlib>=3.5.3
  - numpy>=1.23.2
  - scipy>=1.9.0
  - pandas>=1.4.3
  - xarray>=2022.6.0
  - dask>=2022.8.1
  - netcdf4>=1.6.0
  - wrf-python>=1.3.4
  - utm>=0.7.0
  - f90nml>=1.4.3
  - elevation>=1.1.3
  - rasterio>=1.3.2
  - richdem>=2.3.0
